### PR TITLE
Update StringTableEsCharacters.xml

### PR DESCRIPTION
**Pull request by FJRM95**
Hi! Just finished translation on this file. Hope it works. 

"Issue": On spanish we have differences between male and female nouns or adjectives (eg: Médico/ Médica for doctor or "Ocupado / Ocupada" for Busy). I've translated it to the "generic male" that it is often used when the sex is unknown o is a collective. ¿What do you think guys?

### CODE REVIEW

**Comment by lokatronao** [comment]
I think that depending on the context in the game there are several words that we can translate in male, but not always.

**Comment by Dysp** [comment]
@lokatronao & @FJRM95 

Since I don't speak Spanish, can you agree that this is a proper approach? In that case I will merge the changes into master branch.

**Comment by edumesye** [comment]
I think we should use the "generic male" as it is used in Spanish but it would be much better if the game could discriminate the gender of the character and consequently apply the proper Spanish noun. This sounds like a ton of programming to me, but I'm not into that so don't really know.
In the end, generic male should be the better option to comply with Spanish grammar, although I think we should consider including an @ or "el/la" (male/female articles) before the noun... It's a heated discussion in our society tbh

**Comment by Dysp** [comment]
I'm merging. You can always create another PR to correct already accepted changes.

**Comment by FJRM95** [comment]
> I think we should use the "generic male" as it is used in Spanish but it would be much better if the game could discriminate the gender of the character and consequently apply the proper Spanish noun. This sounds like a ton of programming to me, but I'm not into that so don't really know.
> In the end, generic male should be the better option to comply with Spanish grammar, although I think we should consider including an "doctor/a" (which refers to both genders) or "el/la" (male/female articles) before the noun... It's a heated discussion in our society tbh

Totally agree with you. This weekend i'll try to test al the already-translated strings on the game and check everything fits on the screen and on the context. Given the fact that some strings will have to be changed or corrected, we can modify the gender later. 

Thank you guys for the feedback! Really appreciated it!

**Pull request merged**
